Remove unused variables mlen, uri_len
Remove unused variables that are set with no visible side effect.

/usr/bin/clang-14 -Wall -Wextra -Werror -Wshadow -Wno-sign-compare -Wno-pragmas -Wno-tautological-pointer-compare
Results in 
civetweb/src/civetweb.c:8769:12: error: unused variable 'mlen' [-Werror,-Wunused-variable]
                                size_t mlen = strlen(workdata->f_user)
                                       ^
civetweb/src/civetweb.c:14621:6: error: variable 'uri_len' set but not used [-Werror,-Wunused-but-set-variable]
        int uri_len, ssl_index;